# Generated by Django 5.1.2 on 2024-10-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaivariety',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
