# Generated by Django 5.1.2 on 2024-10-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_rename_data_added_chaivariety_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='chai_variety',
            new_name='chai_varieties',
        ),
    ]
